Syntax 4

SectionVerb {
	EnableSequence [
		cset "name='AIF1DAC1 Volume' 96"
		cset "name='AIF1 Boost' 0"
		cset "name='DAC1 Volume' 96"
		cset "name='DAC1 Switch' on"
		cset "name='SPKOUTL Switch' on"
		cset "name='SPKOUTR Switch' on"
		cset "name='Speaker Mixer Volume' 3"
		cset "name='Speaker Boost Volume' 4"
		cset "name='Speaker Volume' 57"
		cset "name='Headphone Volume' 57"
		cset "name='Headphone Switch' on"
	]

	DisableSequence [
		cset "name='SPKOUTL Switch' off"
		cset "name='SPKOUTR Switch' off"
		cset "name='Headphone Switch' off"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Built-in Stereo Speakers"

	EnableSequence [
		cset "name='SPKOUTL Switch' on"
		cset "name='SPKOUTR Switch' on"
		cset "name='Speaker Volume' 57"
	]

	DisableSequence [
		cset "name='SPKOUTL Switch' off"
		cset "name='SPKOUTR Switch' off"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
	}
}

SectionDevice."Headphones" {
	Comment "Headphone 3.5mm Jack"

	EnableSequence [
		cset "name='Headphone Switch' on"
		cset "name='Headphone Volume' 57"
	]

	DisableSequence [
		cset "name='Headphone Switch' off"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		JackControl "Headphone Jack"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	EnableSequence [
		cset "name='IN1L Switch' on"
		cset "name='IN1R Switch' on"
		cset "name='MIXINL IN1L Switch' on"
		cset "name='MIXINR IN1R Switch' on"
		cset "name='IN1L Volume' 25"
		cset "name='IN1R Volume' 25"
	]

	DisableSequence [
		cset "name='IN1L Switch' off"
		cset "name='IN1R Switch' off"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},0"
		CaptureChannels 2
	}
}
